# -*- coding: utf-8 -*-
"""final17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1i4fwqVN1F24tqitqMMQ7N_EkelQAXa
"""

#นายธนภัทร ประไพรัตน์ เลขที่ 17 ม.4/4
print(" สว้สดีครับผม ยินดีต้อนรับเข้าสู่โปรแกรมเกมทายเลข 1-10")
user_name = input("กรุณากรองชื่อของคุณ : ")
print(f"ยินดีที่ได้รู้จักครับผม {user_name} ")

#โปรแกรมเกมทายตัวเลข 1-10
import random

answer = random.randint(1, 10)   # สุ่มเลข 1-10
guess = int(input("ทายตัวเลข 1-10: "))

if guess == answer:
    print("ทายถูก!")
else:
    print("ทายผิด เลขที่ถูกคือ", answer)